[pytest]
# 测试用例目录
testpaths = testcases

# 用例文件规则
python_files = test_*.py
# 用例类规则
python_classes = Test*
# 用例方法规则
python_functions = test_*

# 编码(-vs:输出详细测试结果；--strict-markers:禁止使用未注册的标记，避免标记写错)
addopts = -vs --strict-markers